spring:
  profiles:
    active: local

---
spring:
  profiles: local

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

    hibernate:
      ddl-auto: update

    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: true

  datasource:
    url: jdbc:mysql://iyoungman-skuniv-mysql-1.chxhgtrfuigt.ap-northeast-2.rds.amazonaws.com:3306/mop?useSSL=false&serverTimezone=Asia/Seoul
    username: root
    password: duddnjsgl912!

  batch:
    job:
      enabled: false

server:
    port: 8090

logging:
  level:
    org:
      springframework:
        batch: DEBUG

#spring.batch.job.names: ${job.name:NONE}