spring:
  profiles:
    active: local

---
spring:
  profiles: local

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

    hibernate:
      ddl-auto: update

    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: true

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mop?useSSL=false&serverTimezone=Asia/Seoul
    username: iyoungman
    password: duddnjsgl912!

  batch:
    job:
      enabled: false


#spring.batch.job.names: ${job.name:NONE}
logging.level.org.springframework.batch: DEBUG